english_learning/urls.py
from django.urls import path

from . import views

app_name = 'flashcards'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('add_words/', views.add_words, name='add_words'),
    path('add_texts/', views.add_texts, name='add_texts'),
    
    path('nav_bar/', views.nav_bar, name='nav_bar'),
    path('search/', views.search, name='search'),

    path('words_list/', views.AllWordsView.as_view(), name='words_list'),
    path('today_test/', views.today_test_start, name='today_test_start'),#views.TodayTestView.as_view()
    path('today_test/<str:word>', views.today_test, name='today_test'),
    path('today_test/<str:word>/pass/', views.today_test_pass, name='today_test_pass'),
    path('today_test/<str:word>/fail/', views.today_test_fail, name='today_test_fail'),
    path('today_test/<str:word>/again/', views.today_test_again, name='today_test_again'),
    path('words_match/', views.words_match, name='words_match'),
    path('learn_words/', views.ToLearnWordsView.as_view(), name='learn_words'),

    # path('today_word_practice/', views.today_word_practice, name='today_word_practice'),
    # path('today_text_practice/', views.today_text_practice, name='today_text_practice'),

    path('today_text_test/', views.today_text_test_start, name='today_text_test_start'),
    path('today_text_test/<int:text_id>', views.today_text_test, name='today_text_test'),
    path('texts_list/', views.AllTextsView.as_view(), name='texts_list'),
    # path('learn_text/', views.ToLearnWordsView.as_view(), name='learn_text')
    
    # language
    path('en/', views.english, name='english'),
    path('jp/', views.japanese, name='japanese'),
]

english_learning/models.py
from django.db import models
from django.utils import timezone
import datetime

class Flashcards(models.Model):
    # days for learning
    forgetting_curve_days = [0, 1, 2, 3, 5, 10, 30 ,60, 90]
    STATUS_choices = [(i, i) for i in forgetting_curve_days]
    Next_status = {0:1, 1:2, 2:3, 3:5, 5:10, 10:30, 30:60 , 60:90}
    
    # part of speech
    NOUN = 'noun'
    VERB = "verb"
    ADJ = "adjective"
    ADV = "adverb"
    PRONOUN = "pronoun"
    PREPOSITION = 'preposition'
    CONJUNCTION = 'conjunction'
    POS_choices = [
        (NOUN, 'noun'),
        (VERB, 'verb'),
        (ADJ, 'adjective'),
        (ADV, 'adverb'),
        (PRONOUN, 'pronoun'),
        (PREPOSITION, 'preposition'),
        (CONJUNCTION, 'conjunction')
    ]

    # language
    ENGLISH = 'en'
    JAPANESE = 'jp'
    LANGUAGE_choices = [
        (ENGLISH, 'en'),
        (JAPANESE, 'jp')
    ]

    word = models.CharField(max_length=50, blank=False)
    meaning = models.TextField(max_length=300, blank=False)
    example_sentence = models.TextField(max_length=300, blank=True)
    last_answer = models.TextField(max_length=300, blank=True)
    pos = models.CharField(max_length=11, choices=POS_choices, default=POS_choices[0])
    status = models.PositiveSmallIntegerField(choices=STATUS_choices, default=0)
    next_to_learn = models.DateField(default=timezone.now)
    language = models.CharField(max_length=5, choices=LANGUAGE_choices, default='en')
    # last_test_result = models.TextField(max_length=300)

    def __str__(self):
        return self.word

class Flashcard_Text(models.Model):
    # days for learning
    forgetting_curve_days = [0, 1, 2, 3, 5, 10, 30 ,60, 90]
    STATUS_choices = [(i, i) for i in forgetting_curve_days]
    Next_status = {0:1, 1:2, 2:3, 3:5, 5:10, 10:30, 30:60 , 60:90}

    # language
    ENGLISH = 'en'
    JAPANESE = 'jp'
    LANGUAGE_choices = [
        (ENGLISH, 'en'),
        (JAPANESE, 'jp')
    ]
    
    text_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, blank=True)
    text = models.TextField(blank=False)
    status = models.PositiveSmallIntegerField(choices=STATUS_choices, default=0)
    next_to_learn = models.DateField(default=timezone.now)
    language = models.CharField(max_length=5, choices=LANGUAGE_choices, default='en')


    def __str__(self):
        return self.title

english_learning/forms.py
from django import forms
from flashcards.models import Flashcards, Flashcard_Text
import datetime

class FlashcardsForm(forms.ModelForm):
    forgetting_curve_days = [0, 1, 2, 3, 5, 10, 30 ,60, 90]
    STATUS_choices = [(i, i) for i in forgetting_curve_days]
    
    # part of speech
    NOUN = 'noun'
    VERB = "verb"
    ADJ = "adjective"
    ADV = "adverb"
    PRONOUN = "pronoun"
    PREPOSITION = 'preposition'
    CONJUNCTION = 'conjunction'
    POS_choices = [
        (NOUN, 'noun'),
        (VERB, 'verb'),
        (ADJ, 'adjective'),
        (ADV, 'adverb'),
        (PRONOUN, 'pronoun'),
        (PREPOSITION, 'preposition'),
        (CONJUNCTION, 'conjunction')
    ]

    # language
    ENGLISH = 'en'
    JAPANESE = 'jp'
    LANGUAGE_choices = [
        (ENGLISH, 'en'),
        (JAPANESE, 'jp')
    ]

    word = forms.CharField(max_length=50, help_text="Word: ", widget=forms.Textarea(attrs={'cols': 40, 'rows':5}))
    meaning = forms.CharField(max_length=300, help_text="Meaning: ", widget=forms.Textarea(attrs={'cols': 40, 'rows': 10}))
    example_sentence = forms.CharField(max_length=300, help_text="Example Sentence: ", widget=forms.Textarea(attrs={'cols': 40, 'rows': 20}), required = False)
    pos = forms.ChoiceField(choices=POS_choices, help_text='POS: ')
    status = forms.IntegerField(widget=forms.HiddenInput(), initial=0, required = False)
    next_to_learn = forms.DateField(widget=forms.HiddenInput(), initial=datetime.date.today(), required = False)
    language = forms.ChoiceField(choices=LANGUAGE_choices, help_text='Language: ')

    class Meta:
        model = Flashcards
        fields = '__all__'


class FlashcardTextForm(forms.ModelForm):
    forgetting_curve_days = [0, 1, 2, 3, 5, 10, 30 ,60, 90]
    STATUS_choices = [(i, i) for i in forgetting_curve_days]

    # language
    ENGLISH = 'en'
    JAPANESE = 'jp'
    LANGUAGE_choices = [
        (ENGLISH, 'en'),
        (JAPANESE, 'jp')
    ]

    title = forms.CharField(max_length=100, help_text="Title: ", widget=forms.Textarea(attrs={'cols': 40, 'rows':5}))
    text = forms.CharField(help_text="Text: ", widget=forms.Textarea(attrs={'cols': 40, 'rows':20}), required = False)
    status = forms.IntegerField(widget=forms.HiddenInput(), initial=0, required = False)
    next_to_learn = forms.DateField(widget=forms.HiddenInput(), initial=datetime.date.today(), required = False)
    language = forms.ChoiceField(choices=LANGUAGE_choices, help_text='Language: ')


    class Meta:
        model = Flashcard_Text
        fields = '__all__'

english_learning/views.py
from django.http import HttpResponseRedirect, HttpResponse
from .models import Flashcards, Flashcard_Text
from django.views import generic
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import FlashcardsForm, FlashcardTextForm
from django.contrib import messages
import datetime
from django.utils import timezone
from django.core.paginator import Paginator
from gtts.templatetags.gTTS import say


def home_page(request):
    return render(request, 'flashcards/home_page.html')


# WORD
class ToLearnWordsView(generic.ListView):
    context_object_name = 'flashcards'
    template_name = 'flashcards/learn_words.html'

    paginate_by = 20
    model = Flashcards

    def get_queryset(self):
        """Return all users."""
        return Flashcards.objects.filter(next_to_learn__lte=timezone.now()).filter(language=self.request.session['lang']).order_by('-next_to_learn')

def add_words(request):
    if request.method == 'POST':
        form = FlashcardsForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            messages.success(request, 'Thank you for adding')

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
            # return render(request, 'flashcards/add_words.html', {'form': form})
        else:
            print(form.errors)
    else:
        form = FlashcardsForm()
    
    return render(request, 'flashcards/add_words.html', {'form': form})

def words_match(request):
    
    return HttpResponse('hello4')

class AllWordsView(generic.ListView):
    context_object_name = 'flashcards'
    template_name = 'flashcards/all_words.html'

    paginate_by = 20
    model = Flashcards

    def get_queryset(self):
        """Return all users."""
        return Flashcards.objects.order_by('pk').filter(language=self.request.session['lang'])

def today_test_start(request):
    test_words = [word.word for word in Flashcards.objects.filter(next_to_learn__lte=datetime.date.today()).order_by('-next_to_learn')]
    if not test_words:
        return home_page(request)
    request.session['today_test'] = test_words
    request.session['index'] = 0

    return render(request, 'flashcards/test_start.html', {'first_word': request.session['today_test'][0]})

def today_test(request, word):
    if request.method == 'POST':
        current_word = Flashcards.objects.filter(word=word)[0]
        current_word.last_answer = request.POST['example']
        current_word.save()

        if current_word.last_answer == current_word.example_sentence:
            return today_test_pass(request, word)

        return render(request, 'flashcards/today_test_check.html', {'word': current_word})
        
    else:
        #obj = say(language='en', text=word)
        obj = 1
        progress = str(request.session['index']+1) + " \ "+ str(len(request.session['today_test']))

        return render(request, 'flashcards/today_test.html', {'word': word, 'obj':obj, 'progress':progress})

def today_test_pass(request, word):
    current_word = Flashcards.objects.filter(word=word)[0]
    if current_word.status == 90:
         current_word.next_to_learn = datetime.date.today() + datetime.timedelta(days = 10*365)
    else:
        current_word.status = Flashcards.Next_status[current_word.status]
        current_word.next_to_learn = datetime.date.today() + datetime.timedelta(days = current_word.status)
    current_word.save()

    next_index = request.session['index'] + 1
    request.session['index'] += 1

    if next_index >= len(request.session['today_test']):
        return home_page(request)
    return HttpResponseRedirect(reverse('flashcards:today_test', args=(request.session['today_test'][next_index],)))

def today_test_again(request, word):
    current_index = request.session['index']
    return HttpResponseRedirect(reverse('flashcards:today_test', args=(request.session['today_test'][current_index],)))

def today_test_fail(request, word):
    current_word = Flashcards.objects.filter(word=word)[0]
    current_word.status = 0
    current_word.next_to_learn = datetime.date.today() + datetime.timedelta(days = 1)
    current_word.save()

    next_index = request.session['index'] + 1
    request.session['index'] += 1

    if next_index >= len(request.session['today_test']):
        return home_page(request)
    return HttpResponseRedirect(reverse('flashcards:today_test', args=(request.session['today_test'][next_index],)))


# # PRACTICING
# def today_word_practice(request):
    
# TEXT
def add_texts(request):
    if request.method == 'POST':
        form = FlashcardTextForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            messages.success(request, 'Thank you for adding')

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = FlashcardTextForm()
    
    return render(request, 'flashcards/add_texts.html', {'form': form})
def today_text_test_start(request):
    if request.method == 'POST':
        to_test_id = int(request.POST['to_test_id'])
        if Flashcard_Text.objects.filter(text_id=to_test_id).exists():
            return HttpResponseRedirect(reverse('flashcards:today_text_test', args=([to_test_id])))

        return HttpResponseRedirect(reverse('flashcards:home_page'))

        
    return render(request, 'flashcards/text_test_start.html')

def today_text_test(request, text_id):
    if request.method == 'POST':
        text = Flashcard_Text.objects.filter(text_id=to_test_id)[0]

        return HttpResponse('hello')
    
    else:
        return render(request, 'flashcards/today_text_test.html', {'text_id': text_id})

class AllTextsView(generic.ListView):
    context_object_name = 'texts_flashcards'
    template_name = 'flashcards/all_texts.html'

    paginate_by = 1
    model = Flashcard_Text

    def get_queryset(self):
        """Return all users."""
        return Flashcard_Text.objects.order_by('pk').filter(language=self.request.session['lang'])

# NAV BAR
def nav_bar(request):
    return render(request, 'flashcards/nav_bar.html')

# LANGUAGE
def english(request):
    request.session['lang'] = 'en'
    return home_page(request)

def japanese(request):
    request.session['lang'] = 'jp'
    return home_page(request)

# Search
def search(request):
    if request.method == 'POST':
        searched_word = request.POST['search_word']
        return search_show_word(request, searched_word)
    return home_page(request)

def search_show_word(request, searched_word):
    try:
        words = Flashcards.objects.filter(word__contains=searched_word)
        return render(request, 'flashcards/search_show_word.html', {'words': words})
    except IndexError:
        return home_page(request)

english_learning/templates/flashcards/add_texts.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new text </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="text_container">
		    	<h1 style='text-align: center;font-size:60px;'> Add a new text </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'flashcards:add_texts' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

english_learning/templates/flashcards/add_words.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new word </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add a new word </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'flashcards:add_words' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

english_learning/templates/flashcards/all_texts.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Learn Words </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/text_flashcards.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<h1 style="text-align: center;font-size:60px;margin-top: 100px;"> Here are the list of all texts</h1>
	    	{% for t in page_obj %}
	    	<div class="container">
	    		<div class="face">
	    			{% if t.title %}
		  			<div class='title'> {{ t.title}} </div><br>
		  			<hr>
		  			<div class='text'> {{ t.text|linebreaksbr }} </div>
		  			{% else %}
		  			<div class='sentence'> {{ t.text|linebreaksbr }} </div>
		  			{% endif %}	  			
		  		</div>
	  		</div>
	  		{% endfor %}

	  		<div class="pagination">
			    <span class="step-links">
			        {% if page_obj.has_previous %}
			            <a href="?page=1">&laquo; first</a>
			            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			        </span>

			        {% if page_obj.has_next %}
			            <a href="?page={{ page_obj.next_page_number }}">next</a>
			            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			        {% endif %}
			    </span>
			</div>
	  		<script src="{% static 'flashcards/flashcards.js' %}"></script> 
	  		<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>

	  		
	  	</body>
	 </html>

english_learning/templates/flashcards/all_words.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Learn Words </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/flashcards.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<h1 style="text-align: center;font-size:60px;margin-top: 100px;"> Here are the list of all words</h1>
	    	{% for w in page_obj %}
	    	<div class="container">
	  			<div class='card'>
		  			<div class="face front">{{ w.word }}</div>
	                <div class="face back">{{ w.meaning }}<br><br><br>{{ w.example_sentence|linebreaksbr }}</div>
	      		</div>
	  		</div>
	  		{% endfor %}

	  		<div class="pagination">
			    <span class="step-links">
			        {% if page_obj.has_previous %}
			            <a href="?page=1">&laquo; first</a>
			            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			        </span>

			        {% if page_obj.has_next %}
			            <a href="?page={{ page_obj.next_page_number }}">next</a>
			            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			        {% endif %}
			    </span>
			</div>
	  		<script src="{% static 'flashcards/flashcards.js' %}"></script> 
	  		<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>

	  		
	  	</body>
	 </html>

english_learning/templates/flashcards/home_page.html
<!--
add words
learn words
show all words
today test
word meaning match
-->
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Home Page </title>
	    	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    	{% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/nav_bar.css' %}">
            <style>
            	body{
            		background-color: lightblue;
            	}
            </style>
	    </head>

	    <body>
	    	<!-- <div class="topnav">
			    <a href="{% url 'flashcards:add_words' %}">Add new word</a>
	    		<a href="{% url 'flashcards:learn_words' %}">Learn words</a>
	    		<a href="{% url 'flashcards:words_list' %}">All words</a>
	    		<a href="{% url 'flashcards:today_test_start' %}">Today's Test</a>
	    		<a href="{% url 'flashcards:words_match' %}">Words match</a>
			</div> -->
			<div id="nav-placeholder"> </div>

				<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
	    </body>
	</html>

english_learning/templates/flashcards/learn_words.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Learn Words </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/flashcards.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<h1 style="text-align: center;font-size:60px;margin-top: 60px;"> Here are the words for today</h1>
	    	{% for w in page_obj %}
	    	<div class="container">
	  			<div class='card'>
		  			<div class="face front">{{ w.word }} ({{ w.pos }})</div>
	                <div class="face back">{{ w.meaning }}<br><br><br>{{ w.example_sentence|linebreaksbr }}</div>
	      		</div>
	  		</div>
	  		{% endfor %}

			<div class="pagination">
			    <span class="step-links">
			        {% if page_obj.has_previous %}
			            <a href="?page=1">&laquo; first</a>
			            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			        </span>

			        {% if page_obj.has_next %}
			            <a href="?page={{ page_obj.next_page_number }}">next</a>
			            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			        {% endif %}
			    </span>
			</div>


				<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
	  		<script src="{% static 'flashcards/flashcards.js' %}"></script> 
	  	</body>
	 </html>

english_learning/templates/flashcards/nav_bar.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Home Page </title>
	    	{% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/nav_bar.css' %}">
	    	<style>
	    		a {color: inherit;}
	    	</style>
	    </head>

	    <body>
	    	<div class="topnav">
	    		<a href="{% url 'flashcards:home_page' %}">Home Page</a>

	    		<div class="dropdown">
	    			<button class="dropbtn">Adding</button>
	    			<div class="dropdown-content">
					    <a href="{% url 'flashcards:add_words' %}">Add new word</a>
			    		<a href="{% url 'flashcards:add_texts' %}">Add new text</a>
			    	</div>
			    </div>

	    		<div class="dropdown">
	    			<button class="dropbtn">Words Learning</button>
	    			<div class="dropdown-content">
			    		<a href="{% url 'flashcards:learn_words' %}">Learn words</a>
			    		<a href="{% url 'flashcards:words_list' %}">All words</a>
			    	</div>
			    </div>

			    <div class="dropdown">
	    			<button class="dropbtn">Texts Learning</button>
	    			<div class="dropdown-content">
			    		<!-- <a href="{% url 'flashcards:learn_words' %}">Learn texts</a> -->
			    		<a href="{% url 'flashcards:texts_list' %}">All texts</a>
			    	</div>
			    </div>

			    <div class="dropdown">
	    			<button class="dropbtn">Testing</button>
	    			<div class="dropdown-content">
			    		<a href="{% url 'flashcards:today_test_start' %}">Today's word test</a>
			    		<a href="{% url 'flashcards:today_text_test_start' %}">Today's text test</a>
			    		<a href="{% url 'flashcards:words_match' %}">Words match</a>
			    	</div>
			    </div>

			     <div class="dropdown">
	    			<button class="dropbtn">Language</button>
	    			<div class="dropdown-content">
			    		<a href="{% url 'flashcards:english' %}">English</a>
			    		<a href="{% url 'flashcards:japanese' %}">Japanese</a>
			    	</div>
			    </div>

			    <div class="search">
		    		<form action="{% url 'flashcards:search' %}" method="post" >
		    			{% csrf_token %}
					      <input type="search" style="height: 230px;" name='search_word'>
					      <button type="submit">Search</button>
	    			</form>
	    		</div>
			</div>
	    </body>
	</html>

english_learning/templates/flashcards/search_show_word.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Searched Word's Flashcard </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/flashcards.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<h1 style="text-align: center;font-size:60px;margin-top: 60px;"> Searched word</h1>
	    	{% for word in words %}
	    	<div class="container">
	  			<div class='card'>
		  			<div class="face front">{{ word.word }}</div>
	                <div class="face back">{{ word.meaning }}<br><br><br>{{ word.example_sentence }}</div>
	      		</div>
	  		</div>
	  		{% endfor %}

				<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
	  		<script src="{% static 'flashcards/flashcards.js' %}"></script> 
	  	</body>
	 </html>

english_learning/templates/flashcards/test_start.html
<!DOCTYPE>
    <html>
        <head> 
            <title> Start the Test </title>
            {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/test.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
        </head>

        <body>
        	<div id="nav-placeholder"> </div>
            <div class='start_button'>
            		<a href="{% url 'flashcards:today_test' first_word%}" class="button">Start Quiz</a>
            </div>
            <script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
        </body>
    </html>

english_learning/templates/flashcards/today_test_check.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Today Test </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'flashcards/test.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<h1 style='text-align: center;font-size:60px;margin-top: 100px;'> Today's test </h1>
            <div class='container'>
                <div class='card'>
                       {{ word.word }}<br>
                       <div class='example_sentence' style='margin-top:50px'>
                           <p><b>Correct answer:</b> {{word.example_sentence}}</p>
                           <p><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Your answer: </b> {{word.last_answer}}</p>
                           <div class='check_button'>
	                           <a href="{% url 'flashcards:today_test_pass' word.word%}" class="button" style='font-size:20px;'>pass</a>
	                       </div>
	                       <div class='space'></div>
	                       <div class='check_button'>
	                           <a href="{% url 'flashcards:today_test_again' word.word%}" class="button" style='font-size:20px;'>again</a>
	                       </div>
	                       <div class='space'></div>
	                       <div class='check_button'>
	                           <a href="{% url 'flashcards:today_test_fail' word.word%}" class="button"style='font-size:20px;'>fail</a>
	                       </div>
	                   </div>
                   		</div>
                </div>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'flashcards:nav_bar' %}");
				});
				</script>
        </body>
    </html>