english_learning/urls.py
from django.urls import path

from . import views

app_name = 'flashcards'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('add_words/', views.add_words, name='add_words'),
    path('add_texts/', views.add_texts, name='add_texts'),
    
    path('nav_bar/', views.nav_bar, name='nav_bar'),
    path('search/', views.search, name='search'),

    path('words_list/', views.AllWordsView.as_view(), name='words_list'),
    path('today_test/', views.today_test_start, name='today_test_start'),#views.TodayTestView.as_view()
    path('today_test/<str:word>', views.today_test, name='today_test'),
    path('today_test/<str:word>/pass/', views.today_test_pass, name='today_test_pass'),
    path('today_test/<str:word>/fail/', views.today_test_fail, name='today_test_fail'),
    path('today_test/<str:word>/again/', views.today_test_again, name='today_test_again'),
    path('words_match/', views.words_match, name='words_match'),
    path('learn_words/', views.ToLearnWordsView.as_view(), name='learn_words'),

    # path('today_word_practice/', views.today_word_practice, name='today_word_practice'),
    # path('today_text_practice/', views.today_text_practice, name='today_text_practice'),

    path('today_text_test/', views.today_text_test_start, name='today_text_test_start'),
    path('today_text_test/<int:text_id>', views.today_text_test, name='today_text_test'),
    path('texts_list/', views.AllTextsView.as_view(), name='texts_list'),
    # path('learn_text/', views.ToLearnWordsView.as_view(), name='learn_text')
    
    # language
    path('en/', views.english, name='english'),
    path('jp/', views.japanese, name='japanese'),
]

japanese_learning/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'jp_learning'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('add_vocabulary/', views.add_vocabulary, name='add_vocabulary'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_sentence/', views.add_sentence, name='add_sentence'),
    path('add_sentence_category/', views.add_sentence_category, name='add_sentence_category'),
    path('add_grammer/', views.add_grammer, name='add_grammer'),
    path('add_grammer_test/', views.add_grammer_test, name='add_grammer_test'),
    path('add_grammer_category/', views.add_grammer_category, name='add_grammer_category'),
    
    path('nav_bar/', views.nav_bar, name='nav_bar'),  

    # List
    path('list_home_page/', views.list_home_page, name='list_home_page'),
    path('list_home_page/<int:top_cat_id>/', views.list_cat_home_page, name='list_cat_home_page'),
    re_path(r'^list_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/$', views.category_list, name='category_list'),

    path('list_sentence_home_page/', views.list_sentence_home_page, name='list_sentence_home_page'),
    path('list_sentence_home_page/<int:top_cat_id>/', views.list_sentence_cat_home_page, name='list_sentence_cat_home_page'),
    re_path(r'^list_sentence_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/$', views.category_sentence_list, name='category_sentence_list'),

    path('list_grammer_home_page/', views.list_grammer_home_page, name='list_grammer_home_page'),
    path('list_grammer_home_page/<int:top_cat_id>/', views.list_grammer_cat_home_page, name='list_grammer_cat_home_page'),
    re_path(r'^list_grammer_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/$', views.category_grammer_list, name='category_grammer_list'),

    # Practice

    path('practice_home_page/', views.practice_home_page, name='practice_home_page'),
    path('practice_home_page/<int:top_cat_id>/', views.practice_cat_home_page, name='practice_cat_home_page'),
    # re_path(r'^practice_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/$', views.practice, name='practice'),
    # re_path(r'^practice_home_page/([0-9]+)/([0-9]+)/start/$', views.voca_test_start, name='voca_test_start'),
    # #re_path(r'^practice_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/start/(?P<translate>[0-1])/$', views.voca_test_start, name='voca_test_start'),
    # re_path(r'^practice_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/listening/(?P<voca_id>[0-9]+)/$', views.voca_listening, name='voca_listening'),
    # re_path(r'^practice_home_page/([0-9]+)/(?P<cat_id>[0-9]+)/translating/(?P<voca_id>[0-9]+)/$', views.voca_translating, name='voca_translating'),
    # re_path('practice_sentence_home_page/category/voca_result/', views.voca_result, name='voca_result'),
    
    path('practice_home_page/category/<int:cat_id>/', views.practice, name='practice'),
    path('practice_home_page/category/<int:cat_id>/start/<int:translate>', views.voca_test_start, name='voca_test_start'),
    path('practice_home_page/category/listening/<int:voca_id>/', views.voca_listening, name='voca_listening'),
    path('practice_home_page/category/translating/<int:voca_id>/', views.voca_translating, name='voca_translating'),
    path('practice_sentence_home_page/category/voca_result/', views.voca_result, name='voca_result'),
    

    path('practice_sentence_home_page/', views.practice_sentence_home_page, name='practice_sentence_home_page'),
    path('practice_sentence_home_page/<int:top_cat_id>/', views.practice_sentence_cat_home_page, name='practice_sentence_cat_home_page'),
    path('practice_sentence_home_page/category/<int:cat_id>/', views.sent_practice, name='sent_practice'),
    path('practice_sentence_home_page/category/<int:cat_id>/start/<int:translate>', views.sent_test_start, name='sent_test_start'),
    # path('practice_sentence_home_page/category/londond_hearts/', views.londond_hearts, name='londond_hearts'),
    path('practice_sentence_home_page/category/listening/<int:sent_id>/', views.sent_listening, name='sent_listening'),
    path('practice_sentence_home_page/category/translating/<int:sent_id>/', views.sent_translating, name='sent_translating'),
    path('practice_sentence_home_page/category/sent_result/', views.sent_result, name='sent_result'),

    
    path('practice/<int:voca_or_sent_id>/<int:voca>/<int:translate>/pass/', views.test_pass, name='test_pass'),
    path('practice/<int:voca_or_sent_id>/<int:voca>/<int:translate>/fail/', views.test_fail, name='test_fail'),
    path('practice/<int:voca>/<int:translate>/again/', views.test_again, name='test_again'),

#     path('practice_overview/', views.practice_overview, name='practice_overview'),
]

japanese_learning/views.py
from django.shortcuts import render
from .models import Vocabulary, Category, Sentence, Sentence_Category, Top_Category, Top_Sentence_Category, Grammer, Grammer_Test, Grammer_Category, Top_Grammer_Category
from .forms import VocaForm, CateForm, SenForm, SenCateForm, GrammerForm, GrammerTestForm, GrammerCateForm
import pyttsx3
import time
from django.http import HttpResponseRedirect, HttpResponse
from queue import Queue
from threading import Thread
from django.urls import reverse
from gtts.templatetags.gTTS import say
import datetime
from collections import OrderedDict
from django.core.paginator import Paginator

# BASIC
q = Queue()
engine = pyttsx3.init(debug=True)
engine.setProperty('voice', 'com.apple.speech.synthesis.voice.kyoko')

# HOME PAGE
def home_page(request):
    return render(request, 'japanese_learning/home_page/home_page.html')

# NAV BAR
def nav_bar(request):
    return render(request, 'japanese_learning/nav_bar/nav_bar.html')

# ADDING

def add_vocabulary(request):
    if request.method == 'POST':
        form = VocaForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = VocaForm()
    
    return render(request, 'japanese_learning/adding/add_vocabulary.html', {'form': form})

def add_category(request):
    if request.method == 'POST':
        form = CateForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = CateForm()
    
    return render(request, 'japanese_learning/adding/add_category.html', {'form': form})

def add_sentence(request):
    if request.method == 'POST':
        form = SenForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = SenForm()

    return render(request, 'japanese_learning/adding/add_sentence.html', {'form': form})

def add_sentence_category(request):
    if request.method == 'POST':
        form = SenCateForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = SenCateForm()

    return render(request, 'japanese_learning/adding/add_sentence_category.html', {'form': form})

def add_grammer(request):
    if request.method == 'POST':
        form = GrammerForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = GrammerForm()
    
    return render(request, 'japanese_learning/adding/add_grammer.html', {'form': form})

def add_grammer_test(request):
    if request.method == 'POST':
        form = GrammerTestorm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = GrammerTestForm()
    
    return render(request, 'japanese_learning/adding/add_grammer_test.html', {'form': form})

def add_grammer_category(request):
    if request.method == 'POST':
        form = GrammerCateForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
        else:
            print(form.errors)
    else:
        form = GrammerCateForm()
    
    return render(request, 'japanese_learning/adding/add_grammer_category.html', {'form': form})

# Practicing

def practice_home_page(request):
    cat = Top_Category.objects.all()
    return render(request, 'japanese_learning/practice/vocabulary/practice_home_page.html', {'cats': cat})

def practice_cat_home_page(request, top_cat_id):
    cat = Category.objects.filter(top_cat=top_cat_id)
    return render(request, 'japanese_learning/practice/vocabulary/practice_cat_home_page.html', {'cats': cat})

def practice(request, cat_id): 
    return render(request, 'japanese_learning/practice/vocabulary/listening_translating_voca.html', {'cat_id': cat_id})
   
def voca_test_start(request, cat_id, translate):
    if translate:
        words = Vocabulary.objects.filter(category=cat_id).filter(translating_next_to_learn__lte=datetime.date.today())
    else:
        words = Vocabulary.objects.filter(category=cat_id).filter(listening_next_to_learn__lte=datetime.date.today())

    if not words:
        cat = Top_Category.objects.get(cat=Category.objects.get(id=cat_id).top_cat).id
        return HttpResponseRedirect(reverse('jp_learning:practice_cat_home_page', args=(cat, )))

    request.session['fail'] = []
    request.session['words'] = [word.id for word in words]
    request.session['index'] = 0

    return render(request, 'japanese_learning/practice/vocabulary/voca_test_start.html', {'first_word': request.session['words'][0], 'translate': translate}) 

def voca_listening(request, voca_id):
    current_word = Vocabulary.objects.filter(id=voca_id)[0]
    if request.method == 'POST':
        answer = request.POST['answer']
        example = request.POST.get('example', '')

        if answer == current_word.kanji and example == current_word.example_sentence:
            return test_pass(request, voca_id, 1, 0)

        return render(request, 'japanese_learning/practice/check/test_check.html', {'question': current_word, 'answer': answer, 'example': example, 'voca':1, 'translate': 0})
                
    else:
        chinese = current_word.zh
        voca = say(language='ja', text=current_word.jp)
        try:
            example = say(language='ja', text=current_word.example_sentence)
        except AssertionError:
            example = 0

        progress = str(request.session['words'].index(voca_id)+1) + " \ "+ str(len(request.session['words']))

        return render(request, 'japanese_learning/practice/vocabulary/practice_voca.html', {'translate':False, 'chinese': chinese, 'voca':voca, 'example':example, 'progress': progress})

def voca_translating(request, voca_id):
    current_word = Vocabulary.objects.filter(id=voca_id)[0]
    if request.method == 'POST':
        answer = request.POST['answer']
        example = request.POST.get('example', '')

        if answer == current_word.kanji and example == current_word.example_sentence:
            return test_pass(request, voca_id, 1, 1)

        return render(request, 'japanese_learning/practice/check/test_check.html', {'question': current_word, 'answer': answer, 'example': example, 'voca':1, 'translate': 1})
        
    else:
        chinese = current_word.zh
        progress = str(request.session['words'].index(voca_id)+1) + " \ "+ str(len(request.session['words']))
        example = current_word.example_sentence
       

        return render(request, 'japanese_learning/practice/vocabulary/practice_voca.html', {'translate':True, 'chinese': chinese, 'example':example, 'progress': progress})

def voca_result(request):
    cat = Category.objects.get(cat=Vocabulary.objects.filter(id=request.session['words'][0])[0].category)
    words = [Vocabulary.objects.get(id=voca_id) for voca_id in request.session['words']]
    sucess = len(words) - len(request.session['fail'])
    
    return render(request, 'japanese_learning/practice/result/voca_result.html', {'fail':request.session['fail'], 'words': words, 'cat':cat, 'sucess':sucess})


def practice_sentence_home_page(request):
    cat = Top_Sentence_Category.objects.all()
    return render(request, 'japanese_learning/practice/sentence/practice_sentence_home_page.html', {'cats': cat})

def practice_sentence_cat_home_page(request, top_cat_id):
    cat = Sentence_Category.objects.filter(top_cat=top_cat_id)
    cat = sorted(cat, key=lambda x:int(x.cat), reverse=True)
    print(type(cat))
    return render(request, 'japanese_learning/practice/sentence/practice_sentence_cat_home_page.html', {'cats': cat})

def sent_practice(request, cat_id):
    return render(request, 'japanese_learning/practice/sentence/listening_translating_sent.html', {'cat_id': cat_id})

def sent_test_start(request, cat_id, translate):
    if translate:
        sentences = Sentence.objects.filter(category=cat_id).filter(translating_next_to_learn__lte=datetime.date.today())
        sentences = Sentence.objects.filter(category=cat_id)
    else:
        sentences = Sentence.objects.filter(category=cat_id).filter(listening_next_to_learn__lte=datetime.date.today())
        sentences = Sentence.objects.filter(category=cat_id)

    if not sentences:
        cat = Top_Sentence_Category.objects.get(cat=Sentence_Category.objects.get(id=cat_id).top_cat).id
        return HttpResponseRedirect(reverse('jp_learning:practice_sentence_cat_home_page', args=(cat, )))

    request.session['fail'] = []
    request.session['sentences'] = [sentence.id for sentence in sentences]
    request.session['index'] = 0

    return render(request, 'japanese_learning/practice/sentence/sent_test_start.html', {'first_sentence': request.session['sentences'][0], 'translate': translate}) 

def sent_listening(request, sent_id):
    current_sentence = Sentence.objects.filter(id=sent_id)[0]
    if request.method == 'POST':
        answer = request.POST['answer']

        if answer == current_sentence.kanji:
            return test_pass(request, sent_id, 0, 0)

        return render(request, 'japanese_learning/practice/check/test_check.html', {'question': current_sentence, 'answer': answer, 'voca':0, 'translate': 0})
    else:

japanese_learning/templates/japanese_learning/adding/add_category.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new category </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new category </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_category' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_grammer.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new Grammer </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new grammer </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_grammer' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_grammer_category.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new Grammer category </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new grammer category </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_grammer_category' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_grammer_test.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new Grammer test </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new grammer test </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_grammer_test' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_sentence.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new sentence </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new sentence </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_sentence' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_sentence_category.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new sentence category </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add new sentence category </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_sentence_category' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>

japanese_learning/templates/japanese_learning/adding/add_vocabulary.html
<!DOCTYPE html>
	<html>
	    <head>
	    	<title> Add new word </title>
	        {% load static %}
            <link rel="stylesheet" type="text/css" href="{% static 'japanese_learning/adding.css' %}">
            <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	    </head>

	    <body>
	    	<div id="nav-placeholder"> </div>
	    	<div class="container">
		    	<h1 style='text-align: center;font-size:60px;'> Add a new word </h1>

		    	<table border="1" style="margin:auto;background-color: rgba(181, 215, 228, 0.8);display: relative;">
		    	    <form action="{% url 'jp_learning:add_vocabulary' %}" method="post">
		    	    {% csrf_token %} 	               	
	            	{% for field in form.visible_fields %}
	            	<tr>
	            		<td>{{ field.help_text }}</td>
	            		<td> {{ field }} </td>		
	            	</tr>
				    {% endfor %}
				</table><br><br>	
				<input type="submit" value="Submit" style="margin:0 auto;display:block;">
				</form>
			</div>
			<script>
				$(function(){
				  $("#nav-placeholder").load("{% url 'jp_learning:nav_bar' %}");
				});
				</script>
	  	</body>
	 </html>